profile: coverage.out
local-prefix: "github.com/eagraf/habitat-new"

# Holds coverage thresholds percentages, values should be in range [0-100]
threshold:
  # The minimum coverage that each file should have
  file: 70
  # The minimum coverage that each package should have
  package: 70
  # The minimum total coverage project should have
  total: 70

# Holds regexp rules which will override thresholds for matched files or packages using their paths.
#
# First rule from this list that matches file or package is going to apply new threshold to it. 
# If project has multiple rules that match same path, override rules should be listed in order from 
# specific to more general rules.
override:
  # Increase coverage threshold to 100% for `foo` package (default is 80, as configured above)
  - threshold: 100
    path: ^pkg/lib/foo$

# Holds regexp rules which will exclude matched files or packages from coverage statistics
exclude:
  # Exclude files or packages matching their paths
  paths:
    - \/mocks\/.*?$
    - ^internal\/node\/config
    - ^internal/node/hdb
    - \/fx\.go$
    - \/test_helpers
    - ^pkg\/raft\/transport
    - ^pkg\/raft\/transport
    - ^internal/node/drivers
    - ^internal/node/api
    - ^cmd/node
    - ^internal/node/reverse_proxy/server.go
    - ^internal/node/server/server.go
    - ^internal/frontend
    - ^internal/node/controller/pds.go
    - ^internal/node/controller/auth.go
    - ^internal/docker
    - ^internal/web
    - ^internal/bffauth/cmd
    - ^internal/bffauth/provider.go # File is too small :)
