# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Build the Habitat node binary before reloading
# The options passed to -gcflags enable instrumentation needed for debugging
cmd = "go build -gcflags='all=-N -l' -o /habitat_node ./cmd/node/main.go"
# Binary file yields from `cmd`.
bin = "/habitat_node"
stop_on_error = true

# Execute the node binary with the Delve debugger.
# When in debugging mode, it sometimes helps to have the application block immediately so that you can
# easily debug code that executes near startup. To do this, remove the --continue flag and rebuild the docker
# image.
full_bin = "dlv exec --accept-multiclient --log --headless --listen :4000 --api-version 2 /habitat_node"

# Watch these filename extensions.
include_ext = ["go", "yml"]