reverse_proxy_rules:
  - type: redirect
    id: atphoto_api
    matcher: /atphoto_api
    target: http://host.docker.internal:5002

  - type: redirect
    id: atphoto
    matcher: /atphoto
    target: http://host.docker.internal:5173/atphoto

  - type: redirect
    id: pouch_api
    matcher: /pouch_api
    target: http://host.docker.internal:5234

  - type: redirect
    id: pouch
    matcher: /pouch
    target: http://host.docker.internal:4124/pouch

  - type: redirect
    id: calendar_api
    matcher: /calendar_api
    target: http://host.docker.internal:5235

  - type: redirect
    id: calendar
    matcher: /calendar
    target: http://host.docker.internal:4125/calendar
