packages:
  - path: "github.com/eagraf/habitat-new/core/api"
    output_path: "frontend/types/api.ts"
    exclude_files:
      - habitat_db.go
  - path: "github.com/eagraf/habitat-new/core/state/node"
    output_path: "frontend/types/node.ts"
    include_files:
      - schema.go