/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ServerImport } from './routes/server'
import { Route as LoginImport } from './routes/login'
import { Route as AppStoreImport } from './routes/app-store'
import { Route as AddUserImport } from './routes/add-user'
<<<<<<< HEAD
import { Route as RequireAuthImport } from './routes/_requireAuth'
import { Route as IndexImport } from './routes/index'
import { Route as RequireAuthPrivyTestImport } from './routes/_requireAuth/privy-test'
=======
import { Route as IndexImport } from './routes/index'
>>>>>>> origin/master

// Create/Update Routes

const ServerRoute = ServerImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppStoreRoute = AppStoreImport.update({
  id: '/app-store',
  path: '/app-store',
  getParentRoute: () => rootRoute,
} as any)

const AddUserRoute = AddUserImport.update({
  id: '/add-user',
  path: '/add-user',
  getParentRoute: () => rootRoute,
} as any)

<<<<<<< HEAD
const RequireAuthRoute = RequireAuthImport.update({
  id: '/_requireAuth',
  getParentRoute: () => rootRoute,
} as any)

=======
>>>>>>> origin/master
const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

<<<<<<< HEAD
const RequireAuthPrivyTestRoute = RequireAuthPrivyTestImport.update({
  id: '/privy-test',
  path: '/privy-test',
  getParentRoute: () => RequireAuthRoute,
} as any)

=======
>>>>>>> origin/master
// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
<<<<<<< HEAD
    '/_requireAuth': {
      id: '/_requireAuth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RequireAuthImport
      parentRoute: typeof rootRoute
    }
=======
>>>>>>> origin/master
    '/add-user': {
      id: '/add-user'
      path: '/add-user'
      fullPath: '/add-user'
      preLoaderRoute: typeof AddUserImport
      parentRoute: typeof rootRoute
    }
    '/app-store': {
      id: '/app-store'
      path: '/app-store'
      fullPath: '/app-store'
      preLoaderRoute: typeof AppStoreImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/server': {
      id: '/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof ServerImport
      parentRoute: typeof rootRoute
    }
<<<<<<< HEAD
    '/_requireAuth/privy-test': {
      id: '/_requireAuth/privy-test'
      path: '/privy-test'
      fullPath: '/privy-test'
      preLoaderRoute: typeof RequireAuthPrivyTestImport
      parentRoute: typeof RequireAuthImport
    }
=======
>>>>>>> origin/master
  }
}

// Create and export the route tree

<<<<<<< HEAD
interface RequireAuthRouteChildren {
  RequireAuthPrivyTestRoute: typeof RequireAuthPrivyTestRoute
}

const RequireAuthRouteChildren: RequireAuthRouteChildren = {
  RequireAuthPrivyTestRoute: RequireAuthPrivyTestRoute,
}

const RequireAuthRouteWithChildren = RequireAuthRoute._addFileChildren(
  RequireAuthRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof RequireAuthRouteWithChildren
=======
export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
>>>>>>> origin/master
  '/add-user': typeof AddUserRoute
  '/app-store': typeof AppStoreRoute
  '/login': typeof LoginRoute
  '/server': typeof ServerRoute
<<<<<<< HEAD
  '/privy-test': typeof RequireAuthPrivyTestRoute
=======
>>>>>>> origin/master
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
<<<<<<< HEAD
  '': typeof RequireAuthRouteWithChildren
=======
>>>>>>> origin/master
  '/add-user': typeof AddUserRoute
  '/app-store': typeof AppStoreRoute
  '/login': typeof LoginRoute
  '/server': typeof ServerRoute
<<<<<<< HEAD
  '/privy-test': typeof RequireAuthPrivyTestRoute
=======
>>>>>>> origin/master
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/_requireAuth': typeof RequireAuthRouteWithChildren
=======
>>>>>>> origin/master
  '/add-user': typeof AddUserRoute
  '/app-store': typeof AppStoreRoute
  '/login': typeof LoginRoute
  '/server': typeof ServerRoute
<<<<<<< HEAD
  '/_requireAuth/privy-test': typeof RequireAuthPrivyTestRoute
=======
>>>>>>> origin/master
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
<<<<<<< HEAD
  fullPaths:
    | '/'
    | ''
    | '/add-user'
    | '/app-store'
    | '/login'
    | '/server'
    | '/privy-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/add-user'
    | '/app-store'
    | '/login'
    | '/server'
    | '/privy-test'
  id:
    | '__root__'
    | '/'
    | '/_requireAuth'
    | '/add-user'
    | '/app-store'
    | '/login'
    | '/server'
    | '/_requireAuth/privy-test'
=======
  fullPaths: '/' | '/add-user' | '/app-store' | '/login' | '/server'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-user' | '/app-store' | '/login' | '/server'
  id: '__root__' | '/' | '/add-user' | '/app-store' | '/login' | '/server'
>>>>>>> origin/master
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
<<<<<<< HEAD
  RequireAuthRoute: typeof RequireAuthRouteWithChildren
=======
>>>>>>> origin/master
  AddUserRoute: typeof AddUserRoute
  AppStoreRoute: typeof AppStoreRoute
  LoginRoute: typeof LoginRoute
  ServerRoute: typeof ServerRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
<<<<<<< HEAD
  RequireAuthRoute: RequireAuthRouteWithChildren,
=======
>>>>>>> origin/master
  AddUserRoute: AddUserRoute,
  AppStoreRoute: AppStoreRoute,
  LoginRoute: LoginRoute,
  ServerRoute: ServerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
<<<<<<< HEAD
        "/_requireAuth",
=======
>>>>>>> origin/master
        "/add-user",
        "/app-store",
        "/login",
        "/server"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
<<<<<<< HEAD
    "/_requireAuth": {
      "filePath": "_requireAuth.tsx",
      "children": [
        "/_requireAuth/privy-test"
      ]
    },
=======
>>>>>>> origin/master
    "/add-user": {
      "filePath": "add-user.tsx"
    },
    "/app-store": {
      "filePath": "app-store.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/server": {
      "filePath": "server.tsx"
<<<<<<< HEAD
    },
    "/_requireAuth/privy-test": {
      "filePath": "_requireAuth/privy-test.tsx",
      "parent": "/_requireAuth"
=======
>>>>>>> origin/master
    }
  }
}
ROUTE_MANIFEST_END */
