// Code generated by MockGen. DO NOT EDIT.
// Source: internal/node/controller/controller.go
//
// Generated by this command:
//
//	mockgen -source=internal/node/controller/controller.go -package mocks -destination=internal/node/controller/mocks/mock_controller.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	node "github.com/eagraf/habitat-new/core/state/node"
	gomock "go.uber.org/mock/gomock"
)

// MockNodeController is a mock of NodeController interface.
type MockNodeController struct {
	ctrl     *gomock.Controller
	recorder *MockNodeControllerMockRecorder
}

// MockNodeControllerMockRecorder is the mock recorder for MockNodeController.
type MockNodeControllerMockRecorder struct {
	mock *MockNodeController
}

// NewMockNodeController creates a new mock instance.
func NewMockNodeController(ctrl *gomock.Controller) *MockNodeController {
	mock := &MockNodeController{ctrl: ctrl}
	mock.recorder = &MockNodeControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeController) EXPECT() *MockNodeControllerMockRecorder {
	return m.recorder
}

// AddUser mocks base method.
func (m *MockNodeController) AddUser(userID, username, certificate string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", userID, username, certificate)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockNodeControllerMockRecorder) AddUser(userID, username, certificate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockNodeController)(nil).AddUser), userID, username, certificate)
}

// FinishAppInstallation mocks base method.
func (m *MockNodeController) FinishAppInstallation(userID, registryURLBase, appID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishAppInstallation", userID, registryURLBase, appID)
	ret0, _ := ret[0].(error)
	return ret0
}

// FinishAppInstallation indicates an expected call of FinishAppInstallation.
func (mr *MockNodeControllerMockRecorder) FinishAppInstallation(userID, registryURLBase, appID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishAppInstallation", reflect.TypeOf((*MockNodeController)(nil).FinishAppInstallation), userID, registryURLBase, appID)
}

// GetUserByUsername mocks base method.
func (m *MockNodeController) GetUserByUsername(username string) (*node.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", username)
	ret0, _ := ret[0].(*node.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockNodeControllerMockRecorder) GetUserByUsername(username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockNodeController)(nil).GetUserByUsername), username)
}

// InitializeNodeDB mocks base method.
func (m *MockNodeController) InitializeNodeDB() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeNodeDB")
	ret0, _ := ret[0].(error)
	return ret0
}

// InitializeNodeDB indicates an expected call of InitializeNodeDB.
func (mr *MockNodeControllerMockRecorder) InitializeNodeDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeNodeDB", reflect.TypeOf((*MockNodeController)(nil).InitializeNodeDB))
}

// InstallApp mocks base method.
func (m *MockNodeController) InstallApp(userID string, newApp *node.AppInstallation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallApp", userID, newApp)
	ret0, _ := ret[0].(error)
	return ret0
}

// InstallApp indicates an expected call of InstallApp.
func (mr *MockNodeControllerMockRecorder) InstallApp(userID, newApp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallApp", reflect.TypeOf((*MockNodeController)(nil).InstallApp), userID, newApp)
}

// StartProcess mocks base method.
func (m *MockNodeController) StartProcess(process *node.Process) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartProcess", process)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartProcess indicates an expected call of StartProcess.
func (mr *MockNodeControllerMockRecorder) StartProcess(process any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartProcess", reflect.TypeOf((*MockNodeController)(nil).StartProcess), process)
}
