name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: make build

    - name: Docker Build
      run: make docker-build

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4.0.0

    - name: Test
      run: go test ./... -coverprofile=coverage.out -coverpkg=./...
    
    - name: check test coverage
      uses: vladopajic/go-test-coverage@v2.8.2
      with:
        config: ./.testcoverage.yml

    - name: Build Archives
      run: make archive

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          bin/**/*.tar.gz
          install.sh

    permissions:
      contents: write
 
