name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4.0.0

    - name: Build
      run: go build -v ./...

    - name: Docker Build
      run: make docker-build

    - name: Test
      run: make test
